import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import mongoose, { Document } from 'mongoose';
import { User } from '../../user/entities/user.entity';
import { Flat } from '../../flats/entities/flat.entity';
import { RentStatus } from '../types/rent-status.enum';

export type RentDocument = Rent & Document;

@Schema({ timestamps: true })
export class Rent {
  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true })
  tenant: User;

  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'Flat', required: true })
  flat: Flat;

  @Prop({ type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true })
  owner: User;

  @Prop({ required: true })
  month: string; // Format: "2025-11"

  @Prop({ required: true })
  year: number;

  @Prop({ required: true })
  baseRent: number;

  @Prop({ required: true, default: 0 })
  electricityBill: number;

  @Prop({ required: true, default: 0 })
  gasBill: number;

  @Prop({ required: true, default: 0 })
  waterBill: number;

  @Prop({ required: false, default: 0 })
  serviceBill: number;

  @Prop({ required: true })
  totalAmount: number;

  @Prop({ required: false, default: 0 })
  lateFee: number;

  @Prop({ required: true })
  adjustedTotalAmount: number; // totalAmount + lateFee

  @Prop({ required: true, default: 0 })
  paidAmount: number;

  @Prop({ required: true })
  dueAmount: number;

  @Prop({ required: true, enum: RentStatus, default: RentStatus.PENDING })
  status: RentStatus;

  @Prop({ required: true })
  dueDate: Date;

  @Prop({ required: false })
  paidDate: Date;

  @Prop({ required: false })
  paymentMethod: string;

  @Prop({ required: false })
  note: string;

  @Prop({ required: false, default: false })
  isAutoGenerated: boolean;

  @Prop({ required: false })
  generatedAt: Date;

  @Prop({ required: false })
  receiptNumber: string;
}

export const RentSchema = SchemaFactory.createForClass(Rent);

