import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { Flat, FlatDocument } from '../src/flats/entities/flat.entity';
import { Rent, RentDocument } from '../src/rents/entities/rent.entity';
import { User } from '../src/user/entities/user.entity';
import { RentStatus } from '../src/rents/types/rent-status.enum';

// Helper to generate random number in range
function randomInRange(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

async function bootstrap() {
  console.log('🚀 Starting fake payment generation...\n');
  
  const app = await NestFactory.createApplicationContext(AppModule);
  
  try {
    // Get Mongoose models directly from the connection
    const flatModel = app.get<Model<FlatDocument>>('FlatModel');
    const rentModel = app.get<Model<RentDocument>>('RentModel');
    
    // Find all flats that have tenants (occupied flats)
    const occupiedFlats = await flatModel
      .find({ tenant: { $exists: true, $ne: null } })
      .populate('tenant')
      .populate('user') // This is the owner
      .exec();
    
    console.log(`📊 Found ${occupiedFlats.length} occupied flats with tenants\n`);
    
    if (occupiedFlats.length === 0) {
      console.log('❌ No occupied flats found. Exiting...');
      await app.close();
      return;
    }
    
    const paymentsToCreate: any[] = [];
    
    // Generate payments for October and November 2025
    const months = [
      { month: '2025-10', year: 2025, dueDate: new Date('2025-11-05') },
      { month: '2025-11', year: 2025, dueDate: new Date('2025-12-05') },
    ];
    
    for (const flat of occupiedFlats) {
      const tenant = flat.tenant as any;
      const owner = flat.user as any;
      
      if (!tenant || !owner) {
        console.log(`⚠️  Skipping flat ${flat.name} - missing tenant or owner`);
        continue;
      }
      
      console.log(`📝 Generating payments for tenant: ${tenant.name} in flat: ${flat.name}`);
      
      for (const monthData of months) {
        // Check if payment already exists for this month
        const existingPayment = await rentModel.findOne({
          tenant: tenant._id,
          flat: flat._id,
          month: monthData.month,
        });
        
        if (existingPayment) {
          console.log(`   ⏭️  Payment already exists for ${monthData.month}, skipping...`);
          continue;
        }
        
        // Generate random utility bills
        const electricityBill = randomInRange(500, 2000);
        const gasBill = randomInRange(300, 800);
        const waterBill = randomInRange(200, 500);
        const serviceBill = 0;
        
        const baseRent = flat.rent;
        const totalAmount = baseRent + electricityBill + gasBill + waterBill + serviceBill;
        const lateFee = 0;
        const adjustedTotalAmount = totalAmount + lateFee;
        const paidAmount = 0;
        const dueAmount = adjustedTotalAmount;
        
        const payment = {
          tenant: tenant._id,
          flat: flat._id,
          owner: owner._id,
          month: monthData.month,
          year: monthData.year,
          baseRent,
          electricityBill,
          gasBill,
          waterBill,
          serviceBill,
          totalAmount,
          lateFee,
          adjustedTotalAmount,
          paidAmount,
          dueAmount,
          status: RentStatus.PENDING,
          dueDate: monthData.dueDate,
          isAutoGenerated: false,
        };
        
        paymentsToCreate.push(payment);
        console.log(`   ✅ Created payment for ${monthData.month}: ${adjustedTotalAmount} BDT`);
      }
    }
    
    if (paymentsToCreate.length > 0) {
      console.log(`\n💾 Inserting ${paymentsToCreate.length} payments into database...`);
      const result = await rentModel.insertMany(paymentsToCreate);
      console.log(`✅ Successfully inserted ${result.length} payments!\n`);
    } else {
      console.log('\n⚠️  No new payments to insert (all payments already exist)\n');
    }
    
    // Summary
    console.log('📈 Summary:');
    console.log(`   - Tenants processed: ${occupiedFlats.length}`);
    console.log(`   - Payments created: ${paymentsToCreate.length}`);
    console.log(`   - Months: October 2025, November 2025`);
    console.log('\n✨ Done!\n');
    
  } catch (error) {
    console.error('❌ Error:', error);
  } finally {
    await app.close();
  }
}

bootstrap();
